### ISSUE TITLE
Reestructure project.

### ISSUE THREAD

**Issue by brayvasq** [kommitters/tickspot.js#31]
Since this project will take a new roadmap, we need to clean up the project, restructure it, and remove the code that we don't need. Now the purpose of this project is to build a Tickspot client.

### Tasks
- [x] Close toggl/importers issues.
- [x] Restructure project under v2 api.
- [x] Remove toggl code from this project.
- [x] Think of a new project name.
- [x] Update README (change project description).
- [x] Update CONTRIBUTING.md (remove toggl references, update project links).
